// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockTracker.Server.Data;

namespace StockTracker.Server.Migrations
{
    [DbContext(typeof(WSBDBContext))]
    [Migration("20210130181204_addedDateTime")]
    partial class addedDateTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("StockTracker.Shared.Models.RedditPostModel", b =>
                {
                    b.Property<string>("postID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("downs")
                        .HasColumnType("int");

                    b.Property<int>("numComments")
                        .HasColumnType("int");

                    b.Property<string>("postURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ups")
                        .HasColumnType("int");

                    b.HasKey("postID");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
